<?xml version="1.0" ?>

<!--<!DOCTYPE students SYSTEM "student.dtd">-->

<!DOCTYPE students [
        <!ELEMENT students (student*) >
        <!ELEMENT student (name,age,sex)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT sex (#PCDATA)>
        <!ATTLIST student number ID #REQUIRED>
        ]>

<students>
    <student number="s1">
        <name>张三</name>
        <age>24</age>
        <sex>男</sex>
    </student>

</students>